### ISSUE TITLE
Support for Nextcloud 20

### ISSUE THREAD

**Issue by Kalytis** [qdii/transmission-nc#1]
Hello, I'd like to use this extension on Nextcloud 20, is a support planned any time in the future ?

Thanks by advance !

**Comment by qdii** [comment]
I spinned up a dev instance of Nextcloud 20, and tested it there. It looks like I'd just need to bump the version in the manifest

**Comment by qdii** [comment]
Alright so I did that, and made other changes, but I can't update the app because … I lost my key. So I'm trying to submit a new one :D

**Comment by qdii** [comment]
Should be good in 0.6.5!
