### ISSUE TITLE
Faulty 0.7.3 release!

### ISSUE THREAD

**Issue by GAS85** [qdii/transmission-nc#18]
Hey, in Release [0.7.3](https://github.com/qdii/transmission-nc/tree/0.7.3) you add License and README  Files to the root of the archive, that will prevent NC from update this App:
![image](https://user-images.githubusercontent.com/6813635/229455757-dd36837f-2d78-4b23-be3d-e879c027a128.png)

Nextcloud Logs Error:

![image](https://user-images.githubusercontent.com/6813635/229456534-9f8f2803-9d1e-4076-8d46-cc337322e11a.png)

Comparison to 0.7.2:

![image](https://user-images.githubusercontent.com/6813635/229455161-056ab4d5-5688-4f9c-847b-601e2a010bcf.png)

### (Update) Workaround to install the app:

- Disable the Transmission app
- Delete Transmission from the `apps/` folder.
- Download the new version from: [Nextcloud App Store](https://apps.nextcloud.com/apps/transmission/releases?platform=21#21)
- Extract the only folder back to the `apps` folder without any files from the root of the archive.
- Enable the app again.

**Comment by VictorLzm** [comment]
Hi,
I can confirm we can't install or update with version 0.7.3 because it contains too many files.
`Extracted app transmission has more than 1 folder`

**Comment by qdii** [comment]
Pushed a new version, hopefully better-packaged this time 😅
