### ISSUE TITLE
Configure RPC port

### ISSUE THREAD

**Issue by oddmean** [qdii/transmission-nc#2]
Is it possible to change the RPC **port** value without editing `apps/transmission/lib/Controller/TransmissionController.php`, so any updates on this file within the app wouldn't reset it to '9091' (I have to use a different one)?

**Comment by qdii** [comment]
I'm giving it a stab right now. The Nextcloud framework allows apps to register "settings". If this works, the port would be configurable in the Settings page.

In practice, so far I can't get the settings to show up in the page, nor does any error appears anywhere. So… keep posted!

**Comment by oddmean** [comment]
Those settings could be done via `occ config:transmission:set` and/or `config/config.php`
@qdii Do I get it right?

**Comment by qdii** [comment]
Should be fixed in 0.6.5

![image](https://user-images.githubusercontent.com/1086125/104621784-c5475d80-5690-11eb-9b83-9e0d5dc19e7a.png)

**Comment by thundergreen** [comment]
sorry to return on this subject but the RPC code can't be changed and switches back to 9091. Another stupi question, how does this app know where the server is located? If I would run it on another machine?
