### ISSUE TITLE
Use without transmission in docker

### ISSUE THREAD

**Issue by palight** [qdii/transmission-nc#3]
Hello, 

Would it be possible to open the use of this app to be able to connect to daemon on another host or simply to connect to the daemon installed from official repositary of my distribution (ubuntu) ?

Thanks by advance for your answer

**Comment by oddmean** [comment]
> Hello,
> 
> Would it be possible to open the use of this app to be able to connect to daemon on another host or simply to connect to the daemon installed from official repositary of my distribution (ubuntu) ?
> 
> Thanks by advance for your answer

I'm using the app with transmission-daemon running on the same host with Nextcloud  (Debian testing, no containers used). The app tries to connect to Transmission's RPC on `localhost:9091` so you just have to set transmission-daemon to use this port. BTW one could set another host:port in `apps/transmission/lib/Controller/TransmissionController.php` but this will be reset if the app is updated.

**Comment by palight** [comment]
thank you very much for your answer @oddmean it solved the issue
