### ISSUE TITLE
Can't connect to transmission

### ISSUE THREAD

**Issue by voarsh2** [qdii/transmission-nc#4]
Running NextCloud V18 here.
When I open transmission I get this:
![image](https://user-images.githubusercontent.com/60437695/101237090-0cbfee80-36ce-11eb-90d3-94887a1aa33d.png)

**Comment by qdii** [comment]
This is more likely because transmission is not running. Are you running it user docker-compose?

**Comment by qdii** [comment]
Closing because there is not enough information to diagnose the problem. Please re-open with more information about your setup!
