### ISSUE TITLE
All rpc request returns "no method name"

### ISSUE THREAD

**Issue by lumiere0b** [qdii/transmission-nc#7]
After updating to v0.7.0 (on Nextcloud 21), Transmission app on my Nextcloud stopped working.

On the inspector, I found that `/apps/transmission/rpc` requests responded with `no method name` error.
And I assumed that, at
https://github.com/qdii/transmission-nc/commit/ca9bf003f8bec18ff07709c562bf9d2dec6d613e#diff-a73a3642f8af17147f847bcef5c65a5afd63b170369b88edb6219674342c87b8L52 the request body wasn't set.
So I reverted the change, the app works fine.

Could you fix it or is it your intended code change?

**Comment by qdii** [comment]
Silly me
Thanks for bringing it up!
